# Generated by Django 3.0.8 on 2020-10-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('question_id', models.IntegerField()),
                ('option_a', models.TextField(max_length=50)),
                ('option_b', models.TextField(max_length=50)),
                ('option_c', models.TextField(max_length=50)),
                ('option_d', models.TextField(max_length=50)),
                ('correct_ans', models.CharField(max_length=4)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quiz.Quiz')),
            ],
        ),
    ]
