# Generated by Django 3.0.8 on 2020-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
