# Generated by Django 3.0.8 on 2020-10-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0002_auto_20201017_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
